name: schedule

on:
  workflow_dispatch: #수동으로 돌려보는거
  schedule:
    - cron: "0 * * * *"
      # https://crontab.guru/
      # 5분텀도 가능은 하지만 무료버전은 30분 이상의 텀을 두는게 좋음

jobs:
  make-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 노드 셋업
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: index.js 실행
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node index.js
